### ISSUE TITLE
Automatic scrolling heavily interferes with viewing documentation

### ISSUE THREAD

**Issue by pvgoran** [arangodb/docs-hugo#405]
Some pages at docs.arangodb.com (for example, https://docs.arangodb.com/3.11/components/arangodb-server/options/) start scrolling like crazy (several screens per second) when I use browser's search (or even page's search box at the top) to find a specific part. (I was searching for `rocksdb.block-cache-size`.) Even after the page reaches the end, it doesn't stop: if I try to scroll it up using mouse wheel or keyboard, it immediately scrolls back to the end. I can interrupt this by clicking the "arrow up" button at the bottom right of the page. This scrolling also starts happening if I manually scroll sufficiently deep into the page; looks like it starts when the current section in the TOC column (on the right) reaches the section title that no longer fully fits into the screen (for me, it's either "javascript" or "ldap", depending on currently visible toolbars).

This makes it impossible to use a large portion of these pages.

I see this behaviour in Firefox 115.4.0esr.

In Chromium 119.0.6045.105, the automatic scrolling is also present, but it's very slow: a few pixels per second. Also, in Chromium the page responds to manual scrolling (with mouse or keyboard) with a significant delay (around half a second).

**Comment by nerpaula** [comment]
@pvgoran thanks for reporting this. We were able to reproduce the issue in Firefox 121.0 (x64). However, it seems to occur only when you set the page zoom to 150% or higher. 

We will investigate this matter further. In the meantime, we recommend reducing the page zoom to ensure an optimal use of the documentation.

**Comment by pvgoran** [comment]
Thank you for looking into this!

> However, it seems to occur only when you set the page zoom to 150% or higher.

It's more complex than that. I encounter it with 100% zoom, but I also have layout.css.devPixelsPerPx=1.2 in about:config, and also scale=0.9 in XFCE Display settings (I have no idea how exactly it affects X Window and Firefox; for me, the result is that everything on the screen is a bit larger). If I reduce zoom in Firefox to 90%, the issue is still there. With 80%, it disappears.

Overall, it looks like occurrence of the issue depends on the height of the viewport. On certain zoom level, it occurs when the browser's find toolbar is visible (thus reducing the viewport height), and disappears when the find toolbar is hidden. Similarly, on another zoom level the issue occurs in normal window mode but disappears when I enter full screen mode.

> In the meantime, we recommend reducing the page zoom to ensure an optimal use of the documentation.

Right, this serves as a work-around.

**Comment by Simran-B** [comment]
I'm fairly certain that it doesn't really have to do with zooming etc. but that it occurs whenever the table of contents is taller than the viewport and when a scroll event occurs, the active headline is attempted to be scrolled into view, which causes the wrong container to be scrolled and this causes another scroll event, resulting in a loop. This can potentially be fixed using a different implementation for the ToC scrolling but getting the math right is non-trivial.

**Comment by Simran-B** [comment]
We decided to disable the ToC scrolling for the time being because we couldn't find quick replacement:
https://github.com/arangodb/docs-hugo/pull/446

**Comment by pvgoran** [comment]
Thank you!
