### ISSUE TITLE
Documentation question: what are all the log topics?

### ISSUE THREAD

**Issue by mackler** [arangodb/docs-hugo#514]
Hi, sorry if this is the wrong place to ask this (I can't seem to get onto the slack channel without having an arango email).

On [the documentation page "Log levels" ](https://docs.arangodb.com/3.12/operations/administration/log-levels/)it says:

> For each log topic (authentication, cluster, queries, etc.), you can configure the lowest level to log. 

The documentation says there are log topics, and it identifies three of them and indicates there are others.  But the documentation neither indicates what those other topics are, nor provides any reference to a place where a comprehensive list of log topics can be accessed.  I've tried internet searching and also the "AI" chatbot on the documentation site, with no success.

Is there a complete list of ArangoDB log topics it in the documentation?  If so, I suggest including a link to it on the "Log levels" page.  If not, I suggest considering whether adding that information might potentially be a net benefit for readers who want to know what the _etc_ in “authentication, cluster, queries, etc.” above refers to.

**Comment by Simran-B** [comment]
The description of the `--log.level` startup option has a list of log topics, which you can access with `arangod --help-log` and also see here: https://docs.arangodb.com/stable/components/arangodb-server/options/#--loglevel

You can also find a list in the HTTP API docs, but unfortunately without proper descriptions - for each log message, a topic is set by an engineer, but there is some leeway and ambiguity which makes it difficult to capture what topic is used when:
https://docs.arangodb.com/stable/components/arangodb-server/options/#--loglevel

Adding a link as you suggest to either of the above pieces of content is a good suggestion, thanks!

**Comment by Simran-B** [comment]
Addressed by
- https://github.com/arangodb/docs-hugo/pull/570
- https://github.com/arangodb/docs-hugo/commit/f63648f4069d0dc35826c55d84c748627464453d
- https://github.com/arangodb/docs-hugo/pull/579 (for 3.11)
